Added Polarization Conversion Functions to and from Celestial frame
punch-mission/punchbowl pull request #328
Opened 2024-11-26 19:49 UTC by s0larish

- [ ] Added to_celestial and from_celestial functions to convert polarization to and from celestial frames within starfield removal in Level 3.
- [ ] Added tests for these two functions.

2025-01-21 06:18 UTC, jmbhughes commented
Can you resolve the conflict and pre-commit problems @s0larish ?

2025-03-05 17:42 UTC, jmbhughes commented
pre-commit.ci autofix

2025-03-09 21:06 UTC, jmbhughes requested changes
Please add a changelog entry. More importantly, we need to actually use these functions instead of leaving a todo.

2025-03-09 21:06 UTC, jmbhughes commented on punchbowl/level3/stellar.py
> +#TODO: Pass the outputs through from_celestial() to convert everything back to mzpsolar
Please resolve this todo.

2025-03-09 21:06 UTC, jmbhughes commented on punchbowl/level3/tests/test_stellar.py
>  #     """
Please clean up these commented out sections.

2025-03-19 18:16 UTC, s0larish commented on punchbowl/level3/stellar.py
> +#TODO: Pass the outputs through from_celestial() to convert everything back to mzpsolar
resolved this, but needs to pass data through to_celestial() before creating starfield background

2025-03-21 19:45 UTC, s0larish commented
pre-commit.ci autofix

2025-03-27 20:42 UTC, jmbhughes commented
pre-commit.ci autofix

2025-03-28 17:29 UTC, jmbhughes approved these changes

2025-03-28 17:31 UTC, merged